### ISSUE TITLE
江湖救急

### ISSUE THREAD

**Issue by TinkMingKing** [xiaoping1993/ForStudent#2]
想用用你的源码，有些问题，请帮帮忙，有偿，QQ：294248306

**Comment by xiaoping1993** [comment]
可以啊，你用，代码开源的，我的QQ：1798034013，你的联系方式我已经加了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TinkMingKing"<notifications@github.com&gt;; 
发送时间: 2020年5月12日(星期二) 下午3:53
收件人: "xiaoping1993/ForStudent"<ForStudent@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [xiaoping1993/ForStudent] 江湖救急 (#2)





 
想用用你的源码，有些问题，请帮帮忙，有偿，QQ：294248306

**Comment by xiaoping1993** [comment]
你可以把问题留在github上，我看到会给你回的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TinkMingKing"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 下午3:53
收件人:&nbsp;"xiaoping1993/ForStudent"<ForStudent@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xiaoping1993/ForStudent] 江湖救急 (#2)





 
想用用你的源码，有些问题，请帮帮忙，有偿，QQ：294248306
